theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
color-modes= true
cursorline = true
completion-timeout = 5
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = [
    "mode",
    "spinner",
    "version-control",
    "file-modification-indicator",
    "read-only-indicator",
]

center = [
    "file-name",
]

right = [
    "diagnostics",
    "workspace-diagnostics",

    "separator",

    "position",
    "position-percentage",
    "total-line-numbers",
    
    "separator",

    "file-encoding",
    "file-line-ending",
    "file-type",
]

separator = "│"

diagnostics = ["hint", "info", "warning", "error"]
workspace-diagnostics = ["hint", "info", "warning", "error"]

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.auto-save]
focus-lost = true

[editor.auto-save.after-delay]
enable = true


[keys.normal.space.l]
g = [
    ":write-all",
    ":new",
    ":insert-output lazygit >/dev/tty",
    ":buffer-close!",
    ":redraw",
    ":reload-all",
]

[keys.normal.space.y]
z = [
    ":new",
    ":insert-output yazi >/dev/tty",
    ":buffer-close!",
    ":redraw",
]


