status_symbol_success="✓"

status_symbol_prefix=""
status_symbol_shell="󰧱"

# Square caps
status_cap_left="█"
status_cap_right="█"

status_window_separator=""


set -g status-position top
set -g status-bg "${thm_crust}"
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 100
set -g status on
set -g status-interval 2



set -g message-style \
    "fg=${thm_pink},bg=${thm_crust},align=centre"

set -g message-command-style \
    "fg=${thm_pink},bg=${thm_crust},align=centre"



set -g pane-border-style \
    "fg=${thm_surface0}"

set -g pane-active-border-style \
    "fg=${thm_pink}"



set -g window-status-activity-style \
    "fg=${thm_text},bg=${thm_crust},none"

set -g window-status-separator \
    "${status_window_separator}"

set -g window-status-style \
    "fg=${thm_text},bg=${thm_crust},none"


set -g window-status-current-format \
    "#[fg=${thm_pink},bg=${thm_crust}] \
#I: \
#[fg=${thm_mauve},bg=${thm_crust}]\
(${status_symbol_success}) \
#[fg=${thm_pink},bg=${thm_crust}]\
#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) \
#[fg=${thm_crust},bg=${thm_crust}]"



set -g window-status-format \
    "#[fg=${thm_blue},bg=${thm_crust}]\
#I: \
#[fg=${thm_text},bg=${thm_crust}]\
#W"



set -g status-right \
    "#[fg=${thm_crust},bg=${thm_pink},nobold,nounderscore,noitalics]\
${status_cap_left}\
#[fg=${thm_crust},bg=${thm_pink},nobold,nounderscore,noitalics]\
 ${status_symbol_prefix}  \
#[fg=${thm_text},bg=${thm_surface0}]\
 #W \
#{?client_prefix,#[fg=${thm_mauve}],#[fg=${thm_pink}]}\
#[bg=${thm_surface0}]\
${status_cap_right}\
#{?client_prefix,#[bg=${thm_mauve}],#[bg=${thm_pink}]}\
#[fg=${thm_crust}]\
${status_symbol_shell} \
#[fg=${thm_text},bg=${thm_surface0}]\
 #S "



set -g status-left ""



# Modes werent working anywhere else
set -g clock-mode-colour "${thm_pink}"
set -g mode-style "fg=${thm_pink},bg=${thm_crust},bold"
